// TypeScript types for the AI PM Roadmap Schema
// PRD v4.1 Compliant (5-Node Architecture)
// Updated: Nov 2025

// ============================================================================
// NEW SCHEMA (PRD v4.1 - Task-Based)
// ============================================================================

/**
 * UserContext - Collected by Inquisitor (Node A)
 * Used by Gap Analyst to calculate feasibility
 */
export interface UserContext {
  goal_domain?: "Cognitive" | "Physical" | "Market"; // OPTIONAL - can infer from specific_goal
  specific_goal: string;
  current_skill_level?: "Beginner" | "Intermediate" | "Advanced"; // DEPRECATED - use current_state_description
  target_skill_level?: "Competent" | "Proficient" | "Master"; // DEPRECATED - use desired_outcome
  current_state_description?: string; // Open-ended: "Built 2 React apps, comfortable with hooks, never used TypeScript"
  desired_outcome?: string; // Open-ended: "Ship a production SaaS with 100 paying customers"
  weekly_hours_cap: number;
  deadline_months: number; // ⚠️ MONTHS not weeks!
  budget_tier?: "Free_Only" | "Low_Budget" | "Premium"; // DEPRECATED - use budget_constraint
  budget_constraint?: string; // Open-ended: "Free only", "$100/month max", "Company pays"
  learning_style?: "Visual_Video" | "Text_Documentation" | "Project_Based"; // DEPRECATED - use learning_preferences
  learning_preferences?: string; // Open-ended: "Videos for concepts, docs for reference, podcasts for commute"
  motivation_anchor?: string;
}

/**
 * StrategyBrief - Output from Gap Analyst (Node B)
 * Contains feasibility assessment and negotiation options
 */
export interface StrategyBrief {
  status: "OPTIMAL" | "TIGHT" | "IMPOSSIBLE";
  required_effort_hours: number;
  user_capacity_hours: number;
  discrepancy_percentage?: number;
  negotiation_options?: Array<{
    option: string;
    description: string;
  }>;
}

/**
 * Task - Core unit of work in PRD v4.1
 * Generated by Curator (Node C), enriched by Enricher (Node D)
 */
export interface Task {
  task_id: string; // UUID
  task_name: string;
  task_type: string; // Domain-specific category (e.g., "learn", "drill", "outreach")
  task_category_label?: string; // Human-readable label (e.g., "Learn Concept", "Practice Drill", "Real Outreach")
  estimated_minutes: number;
  description: string;

  // Resource Authority Protocol
  resource_search_query: string; // Curator generates (e.g., "site:youtube.com PingSkills forehand")
  resource_url?: string; // Enricher populates
  resource_title?: string;
  resource_author?: string;
  quality_score?: number; // 0-100 score from QualityResourceFetcher
  quality_warning?: "LOW_CONFIDENCE"; // Set if quality_score < 30
}

/**
 * Week - Collection of tasks for a single week
 */
export interface Week {
  week_number: number;
  goal: string; // Weekly learning goal
  total_minutes: number; // Should equal weekly_hours_cap * 60 (±5%)
  tasks: Task[];
}

/**
 * Roadmap - Top-level roadmap structure (PRD v4.1)
 */
export interface Roadmap {
  roadmap_title: string;
  total_duration_weeks: number;
  phases: Array<{ [phaseName: string]: Week[] }>; // e.g., [{ "Foundation": [Week1, Week2, ...] }]
}

// ============================================================================
// LEGACY SCHEMA (OLD - For Backward Compatibility)
// These types are kept for existing viewer components
// Will be deprecated once viewer is updated to new schema
// ============================================================================

export interface Resource {
  title: string;
  type: string;
  url?: string; // Optional for resources list, required for suggestedResources
  notes?: string; // User notes about this resource
}

export interface Subtask {
  description: string;
  isCompleted: boolean;
  suggestedResources?: Resource[];
}

export interface DeepDiveTopic {
  description: string;
  isCompleted: boolean;
  suggestedResources?: Resource[];
  subtasks?: Subtask[];
  notes?: string; // User notes about this topic
}

export interface Deliverable {
  description: string;
  isCompleted: boolean;
  subtasks?: Subtask[]; // Some deliverables have nested subtasks
  notes?: string; // User notes about this deliverable
}

export interface BuildSection {
  hours: number;
  projectTitle: string;
  description: string;
  technicalStack?: string[];
  components?: string[];
  deliverables?: Deliverable[];
}

export interface ResearchSection {
  hours: number;
  deepDiveTopics?: DeepDiveTopic[];
  resources?: Resource[];
  deliverables?: Deliverable[]; // Some weeks have deliverables in research section
}

export interface ShareSection {
  hours: number;
  artifactTitle: string;
  artifactDescription: string;
  details?: string[];
  tags?: string[];
  deliverables?: Deliverable[]; // Some weeks have deliverables in share section
}

export interface TimeBreakdown {
  build: number;
  research: number;
  share: number;
}

export interface Week {
  weekNumber: number;
  title: string;
  theme: string;
  totalHours: number;
  status: string;
  timeBreakdown: TimeBreakdown;
  buildSection?: BuildSection;
  researchSection?: ResearchSection;
  shareSection?: ShareSection;
  notes?: string; // User notes about this week
}

export interface Phase {
  phaseNumber: number;
  title: string;
  summary: string;
  weekRange: string;
  weeks: Week[];
}

export interface CoreSkill {
  skill: string;
  description: string;
  relevantWeeks: string;
}

export interface Profile {
  description: string;
  experience: string;
}

export interface WeeklyTimeAllocationTemplate {
  monTue: string;
  wedThu: string;
  friSat: string;
  sun: string;
}

export interface Metric {
  description: string;
  isCompleted: boolean;
}

export interface SuccessMetric {
  category: string;
  metrics: Metric[];
}

export interface MasterResourceItem {
  name: string;
  description: string;
}

export interface MasterResource {
  category: string;
  items: MasterResourceItem[];
}

export interface InterviewBank {
  category: string;
  weight: string;
  framework?: string;
  notes?: string;
  questions: string[];
}

export interface DemonstrationMoment {
  category: string;
  items: string[];
}

export interface WeeklyRituals {
  daily: string;
  weekly: string;
  biWeekly: string;
}

export interface RedFlagCheckpoint {
  checkpoint: string;
  items: string[];
  adjustment: string;
}

export interface CompetitiveAdvantage {
  advantage: string;
  description: string;
  leverage?: {
    inInterviews?: string;
    inNetworking?: string;
  };
}

export interface SupplementalSections {
  weeklyTimeAllocationTemplate: WeeklyTimeAllocationTemplate;
  successMetrics: SuccessMetric[];
  masterResources: MasterResource[];
  interviewBank: InterviewBank[];
  demonstrationMoments: DemonstrationMoment[];
  weeklyRituals: WeeklyRituals;
  redFlagsAndAdjustments: RedFlagCheckpoint[];
  competitiveAdvantages: CompetitiveAdvantage[];
  finalMotivation: string;
  nextSteps: string[];
}

/**
 * @deprecated Use new Roadmap interface from PRD v4.1
 * This is kept for backward compatibility with existing viewer components
 */
export interface LegacyRoadmap {
  id?: string; // Database ID
  title: string;
  goal: string;
  startDate: string;
  targetEndDate: string;
  totalDurationWeeks: number;
  timeCommitmentPerWeek: string;
  profile: Profile;
  learningStyle: string;
  coreSkills: CoreSkill[];
  phases: Phase[];
  supplementalSections: SupplementalSections;
}

// Helper type for filtering and search
export interface SearchFilters {
  phase?: number;
  skill?: string;
  status?: string;
  searchTerm?: string;
}

// ============================================================================
// API RESPONSE TYPES (PRD v4.1)
// ============================================================================

/**
 * Inquisitor Interview - Start Response
 */
export interface InquisitorStartResponse {
  status: "interview_started";
  message: string;
  conversation: Array<{
    role: "user" | "assistant";
    content: string;
  }>;
}

/**
 * Inquisitor Interview - Continue Response (SSE Stream)
 */
export interface InquisitorStreamChunk {
  content?: string; // Partial response text
  interview_complete?: boolean; // True when UserContext JSON is output
  error?: string;
}

/**
 * Roadmap Generation Stream Update (SSE)
 * Sent during the 5-node workflow execution
 */
export interface RoadmapStreamUpdate {
  event: "inquisitor" | "gap_analyst" | "curator" | "enricher" | "validator" | "complete" | "error";
  progress: number; // 0-100
  message: string; // User-friendly progress message
  partial_roadmap?: Roadmap; // Only sent on "complete" event
  error?: string; // Only sent on "error" event
}

/**
 * Negotiation State (when Gap Analyst returns IMPOSSIBLE)
 */
export interface NegotiationState {
  status: "IMPOSSIBLE";
  strategy_brief: StrategyBrief;
  user_choice?: "extend_deadline" | "reduce_scope" | "proceed_anyway";
}

/**
 * Validation Result (from Validator - Node E)
 */
export interface ValidationResult {
  status: "APPROVED" | "REJECTED";
  feedback: string;
  issues?: string[]; // Detailed list of validation errors
}

// ============================================================================
// UTILITY TYPES
// ============================================================================

/**
 * Helper to extract weeks from phases
 */
export type WeeksArray = Week[];

/**
 * Helper to extract phase names
 */
export type PhaseName = string;

/**
 * Type guard to check if roadmap is new format
 */
export function isNewRoadmap(roadmap: any): roadmap is Roadmap {
  return (
    roadmap &&
    typeof roadmap.roadmap_title === "string" &&
    typeof roadmap.total_duration_weeks === "number" &&
    Array.isArray(roadmap.phases) &&
    roadmap.phases.every((phase: any) => typeof phase === "object")
  );
}

/**
 * Type guard to check if roadmap is legacy format
 */
export function isLegacyRoadmap(roadmap: any): roadmap is LegacyRoadmap {
  return (
    roadmap &&
    typeof roadmap.title === "string" &&
    Array.isArray(roadmap.phases) &&
    roadmap.phases.every((phase: any) => phase.weeks && Array.isArray(phase.weeks))
  );
}
